#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LatihanDataGrid
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="btr")]
	public partial class DbContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBTR_Customer(BTR_Customer instance);
    partial void UpdateBTR_Customer(BTR_Customer instance);
    partial void DeleteBTR_Customer(BTR_Customer instance);
    partial void InsertBTR_Wilayah(BTR_Wilayah instance);
    partial void UpdateBTR_Wilayah(BTR_Wilayah instance);
    partial void DeleteBTR_Wilayah(BTR_Wilayah instance);
    #endregion
		
		public DbContextDataContext() : 
				base(global::LatihanDataGrid.Properties.Settings.Default.btrConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BTR_Customer> BTR_Customers
		{
			get
			{
				return this.GetTable<BTR_Customer>();
			}
		}
		
		public System.Data.Linq.Table<BTR_Wilayah> BTR_Wilayahs
		{
			get
			{
				return this.GetTable<BTR_Wilayah>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BTR_Customer")]
	public partial class BTR_Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustomerId;
		
		private string _CustomerName;
		
		private string _CustomerCode;
		
		private string _WilayahId;
		
		private string _KlasifikasiId;
		
		private string _HargaTypeId;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Kota;
		
		private string _KodePos;
		
		private string _NoTelp;
		
		private string _NoFax;
		
		private string _Npwp;
		
		private string _Nppkp;
		
		private string _AddressWp;
		
		private string _AddressWp2;
		
		private bool _IsKenaPajak;
		
		private bool _IsSuspend;
		
		private decimal _Plafond;
		
		private decimal _CreditBalance;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerIdChanging(string value);
    partial void OnCustomerIdChanged();
    partial void OnCustomerNameChanging(string value);
    partial void OnCustomerNameChanged();
    partial void OnCustomerCodeChanging(string value);
    partial void OnCustomerCodeChanged();
    partial void OnWilayahIdChanging(string value);
    partial void OnWilayahIdChanged();
    partial void OnKlasifikasiIdChanging(string value);
    partial void OnKlasifikasiIdChanged();
    partial void OnHargaTypeIdChanging(string value);
    partial void OnHargaTypeIdChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnKotaChanging(string value);
    partial void OnKotaChanged();
    partial void OnKodePosChanging(string value);
    partial void OnKodePosChanged();
    partial void OnNoTelpChanging(string value);
    partial void OnNoTelpChanged();
    partial void OnNoFaxChanging(string value);
    partial void OnNoFaxChanged();
    partial void OnNpwpChanging(string value);
    partial void OnNpwpChanged();
    partial void OnNppkpChanging(string value);
    partial void OnNppkpChanged();
    partial void OnAddressWpChanging(string value);
    partial void OnAddressWpChanged();
    partial void OnAddressWp2Changing(string value);
    partial void OnAddressWp2Changed();
    partial void OnIsKenaPajakChanging(bool value);
    partial void OnIsKenaPajakChanged();
    partial void OnIsSuspendChanging(bool value);
    partial void OnIsSuspendChanged();
    partial void OnPlafondChanging(decimal value);
    partial void OnPlafondChanged();
    partial void OnCreditBalanceChanging(decimal value);
    partial void OnCreditBalanceChanged();
    #endregion
		
		public BTR_Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this.OnCustomerNameChanging(value);
					this.SendPropertyChanging();
					this._CustomerName = value;
					this.SendPropertyChanged("CustomerName");
					this.OnCustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerCode", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CustomerCode
		{
			get
			{
				return this._CustomerCode;
			}
			set
			{
				if ((this._CustomerCode != value))
				{
					this.OnCustomerCodeChanging(value);
					this.SendPropertyChanging();
					this._CustomerCode = value;
					this.SendPropertyChanged("CustomerCode");
					this.OnCustomerCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WilayahId", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string WilayahId
		{
			get
			{
				return this._WilayahId;
			}
			set
			{
				if ((this._WilayahId != value))
				{
					this.OnWilayahIdChanging(value);
					this.SendPropertyChanging();
					this._WilayahId = value;
					this.SendPropertyChanged("WilayahId");
					this.OnWilayahIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlasifikasiId", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string KlasifikasiId
		{
			get
			{
				return this._KlasifikasiId;
			}
			set
			{
				if ((this._KlasifikasiId != value))
				{
					this.OnKlasifikasiIdChanging(value);
					this.SendPropertyChanging();
					this._KlasifikasiId = value;
					this.SendPropertyChanged("KlasifikasiId");
					this.OnKlasifikasiIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HargaTypeId", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string HargaTypeId
		{
			get
			{
				return this._HargaTypeId;
			}
			set
			{
				if ((this._HargaTypeId != value))
				{
					this.OnHargaTypeIdChanging(value);
					this.SendPropertyChanging();
					this._HargaTypeId = value;
					this.SendPropertyChanged("HargaTypeId");
					this.OnHargaTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kota", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Kota
		{
			get
			{
				return this._Kota;
			}
			set
			{
				if ((this._Kota != value))
				{
					this.OnKotaChanging(value);
					this.SendPropertyChanging();
					this._Kota = value;
					this.SendPropertyChanged("Kota");
					this.OnKotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KodePos", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string KodePos
		{
			get
			{
				return this._KodePos;
			}
			set
			{
				if ((this._KodePos != value))
				{
					this.OnKodePosChanging(value);
					this.SendPropertyChanging();
					this._KodePos = value;
					this.SendPropertyChanged("KodePos");
					this.OnKodePosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoTelp", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NoTelp
		{
			get
			{
				return this._NoTelp;
			}
			set
			{
				if ((this._NoTelp != value))
				{
					this.OnNoTelpChanging(value);
					this.SendPropertyChanging();
					this._NoTelp = value;
					this.SendPropertyChanged("NoTelp");
					this.OnNoTelpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoFax", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NoFax
		{
			get
			{
				return this._NoFax;
			}
			set
			{
				if ((this._NoFax != value))
				{
					this.OnNoFaxChanging(value);
					this.SendPropertyChanging();
					this._NoFax = value;
					this.SendPropertyChanged("NoFax");
					this.OnNoFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Npwp", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Npwp
		{
			get
			{
				return this._Npwp;
			}
			set
			{
				if ((this._Npwp != value))
				{
					this.OnNpwpChanging(value);
					this.SendPropertyChanging();
					this._Npwp = value;
					this.SendPropertyChanged("Npwp");
					this.OnNpwpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nppkp", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nppkp
		{
			get
			{
				return this._Nppkp;
			}
			set
			{
				if ((this._Nppkp != value))
				{
					this.OnNppkpChanging(value);
					this.SendPropertyChanging();
					this._Nppkp = value;
					this.SendPropertyChanged("Nppkp");
					this.OnNppkpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressWp", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string AddressWp
		{
			get
			{
				return this._AddressWp;
			}
			set
			{
				if ((this._AddressWp != value))
				{
					this.OnAddressWpChanging(value);
					this.SendPropertyChanging();
					this._AddressWp = value;
					this.SendPropertyChanged("AddressWp");
					this.OnAddressWpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressWp2", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string AddressWp2
		{
			get
			{
				return this._AddressWp2;
			}
			set
			{
				if ((this._AddressWp2 != value))
				{
					this.OnAddressWp2Changing(value);
					this.SendPropertyChanging();
					this._AddressWp2 = value;
					this.SendPropertyChanged("AddressWp2");
					this.OnAddressWp2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsKenaPajak", DbType="Bit NOT NULL")]
		public bool IsKenaPajak
		{
			get
			{
				return this._IsKenaPajak;
			}
			set
			{
				if ((this._IsKenaPajak != value))
				{
					this.OnIsKenaPajakChanging(value);
					this.SendPropertyChanging();
					this._IsKenaPajak = value;
					this.SendPropertyChanged("IsKenaPajak");
					this.OnIsKenaPajakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSuspend", DbType="Bit NOT NULL")]
		public bool IsSuspend
		{
			get
			{
				return this._IsSuspend;
			}
			set
			{
				if ((this._IsSuspend != value))
				{
					this.OnIsSuspendChanging(value);
					this.SendPropertyChanging();
					this._IsSuspend = value;
					this.SendPropertyChanged("IsSuspend");
					this.OnIsSuspendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plafond", DbType="Decimal(18,2) NOT NULL")]
		public decimal Plafond
		{
			get
			{
				return this._Plafond;
			}
			set
			{
				if ((this._Plafond != value))
				{
					this.OnPlafondChanging(value);
					this.SendPropertyChanging();
					this._Plafond = value;
					this.SendPropertyChanged("Plafond");
					this.OnPlafondChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditBalance", DbType="Decimal(18,2) NOT NULL")]
		public decimal CreditBalance
		{
			get
			{
				return this._CreditBalance;
			}
			set
			{
				if ((this._CreditBalance != value))
				{
					this.OnCreditBalanceChanging(value);
					this.SendPropertyChanging();
					this._CreditBalance = value;
					this.SendPropertyChanged("CreditBalance");
					this.OnCreditBalanceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BTR_Wilayah")]
	public partial class BTR_Wilayah : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WilayahId;
		
		private string _WilayahName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWilayahIdChanging(string value);
    partial void OnWilayahIdChanged();
    partial void OnWilayahNameChanging(string value);
    partial void OnWilayahNameChanged();
    #endregion
		
		public BTR_Wilayah()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WilayahId", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WilayahId
		{
			get
			{
				return this._WilayahId;
			}
			set
			{
				if ((this._WilayahId != value))
				{
					this.OnWilayahIdChanging(value);
					this.SendPropertyChanging();
					this._WilayahId = value;
					this.SendPropertyChanged("WilayahId");
					this.OnWilayahIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WilayahName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string WilayahName
		{
			get
			{
				return this._WilayahName;
			}
			set
			{
				if ((this._WilayahName != value))
				{
					this.OnWilayahNameChanging(value);
					this.SendPropertyChanging();
					this._WilayahName = value;
					this.SendPropertyChanged("WilayahName");
					this.OnWilayahNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
