<?xml version="1.0" encoding="utf-8"?><Database Name="btr" Class="DbContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JUDE7;Initial Catalog=btr;Integrated Security=True" SettingsObjectName="LatihanDataGrid.Properties.Settings" SettingsPropertyName="btrConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BTR_Customer" Member="BTR_Customers">
    <Type Name="BTR_Customer">
      <Column Name="CustomerId" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="WilayahId" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="KlasifikasiId" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="HargaTypeId" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Kota" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="KodePos" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="NoTelp" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NoFax" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Npwp" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Nppkp" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AddressWp" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="AddressWp2" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="IsKenaPajak" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSuspend" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Plafond" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="CreditBalance" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BTR_Wilayah" Member="BTR_Wilayahs">
    <Type Name="BTR_Wilayah">
      <Column Name="WilayahId" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WilayahName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>